# .github/FUNDING.yml
custom: [
  "https://etherscan.io/address/0x15a308ed14B7c519a474d1856f45bF81d0000D80",
  "https://solscan.io/account/GikaTNTG1DpytsTqwRdcVJ3F7Z2eHHgFZTkkUWxP2VRP",
  "https://www.blockchain.com/explorer/addresses/btc/bc1q2sg0hf2a6vqxsypwt28rwwt625ct3fq5z3na64"
]
